name: CI

on:
  push:
  pull_request:

jobs:
  lint-visual-editor:
    name: "Lint (visual-editor)"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: |
          echo "::remove-matcher owner=eslint-compact::"
          echo "::remove-matcher owner=eslint-stylish::"
      - run: npm install
        working-directory: ./resources/visual-editor
      - run: npm run lint-no-fix
        working-directory: ./resources/visual-editor

  build-visual-editor:
    name: "Test build (visual-editor)"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install
        working-directory: ./resources/visual-editor
      - run: npm run build
        working-directory: ./resources/visual-editor
